/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */
exports.seed = async function(knex) {
  // Deletes ALL existing entries (in development only)
  if (process.env.NODE_ENV === 'development') {
    await knex('vendors').del();
  }

  // Insert seed entries
  const vendors = [
    {
      id: 'n3rrop22-0p3o-7rs1-oo9q-9oo2op613n44',
      company_name: 'Springfield HVAC Services',
      contact_person: 'Tom Johnson',
      title: 'Lead Technician',
      email: 'tom@springfieldhvac.com',
      phone_primary: '+1-555-HVAC-123',
      phone_secondary: '+1-555-867-5309',
      website: 'https://springfieldhvac.com',
      street_address: '789 Industrial Park Drive',
      city: 'Springfield',
      state_province: 'MA',
      postal_code: '01103',
      country: 'US',
      business_license_number: 'MA-HVAC-12345',
      license_expiration_date: new Date('2024-12-31'),
      insurance_provider: 'Commercial Insurance Co',
      insurance_policy_number: 'CIC-HVAC-789123',
      insurance_expiration_date: new Date('2024-06-30'),
      insurance_coverage_amount: 1000000.00,
      service_categories: JSON.stringify(['hvac', 'electrical']),
      specializations: JSON.stringify(['central_air', 'heating_systems', 'ductwork', 'thermostats']),
      services_description: 'Full-service HVAC contractor specializing in residential systems. Installation, maintenance, and repair of heating, ventilation, and air conditioning systems.',
      emergency_services: true,
      warranty_provided: true,
      warranty_duration_months: 12,
      years_in_business: 15,
      number_of_employees: 8,
      business_type: 'llc',
      tax_id: '12-3456789',
      service_areas: JSON.stringify(['Springfield', 'West Springfield', 'Chicopee', 'Holyoke']),
      max_travel_distance_miles: 25,
      business_hours: JSON.stringify({
        monday: { open: '08:00', close: '17:00' },
        tuesday: { open: '08:00', close: '17:00' },
        wednesday: { open: '08:00', close: '17:00' },
        thursday: { open: '08:00', close: '17:00' },
        friday: { open: '08:00', close: '17:00' },
        saturday: { open: '09:00', close: '15:00' },
        sunday: { closed: true }
      }),
      accepts_emergency_calls: true,
      emergency_contact: '+1-555-HVAC-911',
      hourly_rate: 125.00,
      minimum_charge: 95.00,
      free_estimates: true,
      estimate_validity_days: 30,
      accepted_payment_methods: JSON.stringify(['cash', 'check', 'visa', 'mastercard', 'financing']),
      payment_terms_days: 30,
      average_rating: 4.8,
      total_reviews: 47,
      on_time_percentage: 95.00,
      within_budget_percentage: 92.00,
      total_projects_completed: 156,
      certifications: JSON.stringify(['EPA 608 Universal', 'NATE Certified', 'Massachusetts Licensed']),
      licenses: JSON.stringify(['MA HVAC License #12345']),
      bonded: true,
      insured: true,
      background_check_completed: true,
      last_background_check_date: new Date('2023-01-15'),
      vendor_status: 'preferred',
      relationship_type: 'preferred',
      internal_notes: 'Excellent service, always on time. Used for main HVAC installation and maintenance.',
      tags: JSON.stringify(['hvac', 'reliable', 'preferred']),
      preferred_contact_method: 'phone',
      preferred_contact_time: 'Business hours',
      accepts_text_messages: true,
      communication_notes: 'Tom prefers phone calls for urgent issues, email for routine scheduling.',
      authorized_properties: JSON.stringify([]),
      global_vendor: true,
      added_by_user_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11'
    },
    {
      id: 'o4ssqp33-1q4p-8st2-pp0r-0pp3pq724o55',
      company_name: 'Mike\'s Plumbing Solutions',
      contact_person: 'Mike Sullivan',
      title: 'Owner',
      email: 'mike@mikesplumbing.com',
      phone_primary: '+1-555-PIPE-456',
      website: 'https://mikesplumbing.com',
      street_address: '456 Water Street',
      city: 'Springfield',
      state_province: 'MA',
      postal_code: '01105',
      country: 'US',
      business_license_number: 'MA-PLM-67890',
      license_expiration_date: new Date('2024-09-30'),
      insurance_provider: 'Contractors Insurance',
      insurance_policy_number: 'CI-PLM-456789',
      insurance_expiration_date: new Date('2024-05-15'),
      insurance_coverage_amount: 500000.00,
      service_categories: JSON.stringify(['plumbing']),
      specializations: JSON.stringify(['pipe_repair', 'water_heater', 'bathroom_renovation', 'drain_cleaning']),
      services_description: 'Residential and light commercial plumbing services. Specializing in water heater installation, bathroom renovations, and emergency repairs.',
      emergency_services: true,
      warranty_provided: true,
      warranty_duration_months: 6,
      years_in_business: 12,
      number_of_employees: 3,
      business_type: 'sole_proprietor',
      service_areas: JSON.stringify(['Springfield', 'Longmeadow', 'East Longmeadow']),
      max_travel_distance_miles: 15,
      business_hours: JSON.stringify({
        monday: { open: '07:00', close: '16:00' },
        tuesday: { open: '07:00', close: '16:00' },
        wednesday: { open: '07:00', close: '16:00' },
        thursday: { open: '07:00', close: '16:00' },
        friday: { open: '07:00', close: '16:00' },
        saturday: { closed: true },
        sunday: { closed: true }
      }),
      accepts_emergency_calls: true,
      emergency_contact: '+1-555-PIPE-911',
      hourly_rate: 95.00,
      minimum_charge: 75.00,
      free_estimates: true,
      estimate_validity_days: 14,
      accepted_payment_methods: JSON.stringify(['cash', 'check', 'visa', 'mastercard']),
      payment_terms_days: 0, // Pay on completion
      average_rating: 4.6,
      total_reviews: 32,
      on_time_percentage: 88.00,
      within_budget_percentage: 95.00,
      total_projects_completed: 89,
      certifications: JSON.stringify(['Massachusetts Licensed Plumber']),
      licenses: JSON.stringify(['MA Plumbing License #67890']),
      bonded: true,
      insured: true,
      background_check_completed: true,
      last_background_check_date: new Date('2023-03-20'),
      vendor_status: 'active',
      relationship_type: 'occasional',
      internal_notes: 'Good plumber, competitive rates. Used for water heater replacement.',
      tags: JSON.stringify(['plumbing', 'affordable']),
      preferred_contact_method: 'phone',
      preferred_contact_time: 'Early morning or late afternoon',
      accepts_text_messages: false,
      communication_notes: 'Prefers phone calls only. Rarely checks email.',
      authorized_properties: JSON.stringify([]),
      global_vendor: true,
      added_by_user_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11'
    },
    {
      id: 'p5ttqr44-2r5q-9tu3-qq1s-1qq4qr835p66',
      company_name: 'Elite Electrical Services',
      contact_person: 'Jennifer Martinez',
      title: 'Master Electrician',
      email: 'jennifer@eliteelectrical.com',
      phone_primary: '+1-555-ELEC-789',
      website: 'https://eliteelectrical.com',
      street_address: '321 Voltage Avenue',
      city: 'West Springfield',
      state_province: 'MA',
      postal_code: '01089',
      country: 'US',
      business_license_number: 'MA-ELEC-54321',
      license_expiration_date: new Date('2025-03-31'),
      insurance_provider: 'Electrical Contractors Insurance',
      insurance_policy_number: 'ECI-ELEC-321654',
      insurance_expiration_date: new Date('2024-08-15'),
      insurance_coverage_amount: 2000000.00,
      service_categories: JSON.stringify(['electrical', 'smart_home']),
      specializations: JSON.stringify(['panel_upgrade', 'smart_home_automation', 'lighting_design', 'generator_installation']),
      services_description: 'Licensed electrical contractor specializing in residential electrical work, smart home installations, and backup generator systems.',
      emergency_services: true,
      warranty_provided: true,
      warranty_duration_months: 24,
      years_in_business: 8,
      number_of_employees: 5,
      business_type: 'llc',
      tax_id: '98-7654321',
      service_areas: JSON.stringify(['Springfield', 'West Springfield', 'Agawam', 'Westfield']),
      max_travel_distance_miles: 30,
      business_hours: JSON.stringify({
        monday: { open: '08:00', close: '18:00' },
        tuesday: { open: '08:00', close: '18:00' },
        wednesday: { open: '08:00', close: '18:00' },
        thursday: { open: '08:00', close: '18:00' },
        friday: { open: '08:00', close: '18:00' },
        saturday: { open: '08:00', close: '12:00' },
        sunday: { closed: true }
      }),
      accepts_emergency_calls: true,
      emergency_contact: '+1-555-ELEC-911',
      hourly_rate: 150.00,
      minimum_charge: 125.00,
      free_estimates: true,
      estimate_validity_days: 45,
      accepted_payment_methods: JSON.stringify(['check', 'visa', 'mastercard', 'amex', 'financing']),
      payment_terms_days: 30,
      average_rating: 4.9,
      total_reviews: 28,
      on_time_percentage: 98.00,
      within_budget_percentage: 89.00,
      total_projects_completed: 134,
      certifications: JSON.stringify(['Master Electrician', 'Tesla Powerwall Certified', 'Generac Certified']),
      licenses: JSON.stringify(['MA Electrician License #54321']),
      bonded: true,
      insured: true,
      background_check_completed: true,
      last_background_check_date: new Date('2023-06-01'),
      vendor_status: 'active',
      relationship_type: 'occasional',
      internal_notes: 'High-quality work, specializes in smart home tech. More expensive but worth it for complex projects.',
      tags: JSON.stringify(['electrical', 'smart_home', 'premium']),
      preferred_contact_method: 'email',
      preferred_contact_time: 'Any time during business hours',
      accepts_text_messages: true,
      communication_notes: 'Very responsive via email and text. Good at providing detailed estimates.',
      authorized_properties: JSON.stringify([]),
      global_vendor: true,
      added_by_user_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11'
    }
  ];

  await knex('vendors').insert(vendors);
};