[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["cd backend && npm ci"]

[phases.build]
cmds = ["cd backend && npm run build --if-present"]

[start]
cmd = "cd backend && npm start"