[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 60
healthcheckInterval = 5
restartPolicyType = "on_failure" 
restartPolicyMaxRetries = 2

[[deploy.envVars]]
name = "NODE_ENV"
value = "production"

[[deploy.envVars]]
name = "API_VERSION"
value = "v1"