[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[[deploy.envVars]]
name = "NODE_ENV"
value = "production"

[[deploy.envVars]]
name = "API_VERSION"
value = "v1"