[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 120
healthcheckInterval = 10
restartPolicyType = "on_failure" 
restartPolicyMaxRetries = 3
startCommand = "node src/server.js"

[[deploy.envVars]]
name = "NODE_ENV"
value = "production"

[[deploy.envVars]]
name = "API_VERSION"
value = "v1"